# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/t480s/Documentos/netGui-Tool

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/t480s/Documentos/netGui-Tool

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/t480s/Documentos/netGui-Tool/CMakeFiles /home/t480s/Documentos/netGui-Tool//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/t480s/Documentos/netGui-Tool/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named netGui

# Build rule for target.
netGui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 netGui
.PHONY : netGui

# fast build rule for target.
netGui/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netGui.dir/build.make CMakeFiles/netGui.dir/build
.PHONY : netGui/fast

src/arp.o: src/arp.cpp.o
.PHONY : src/arp.o

# target to build an object file
src/arp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netGui.dir/build.make CMakeFiles/netGui.dir/src/arp.cpp.o
.PHONY : src/arp.cpp.o

src/arp.i: src/arp.cpp.i
.PHONY : src/arp.i

# target to preprocess a source file
src/arp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netGui.dir/build.make CMakeFiles/netGui.dir/src/arp.cpp.i
.PHONY : src/arp.cpp.i

src/arp.s: src/arp.cpp.s
.PHONY : src/arp.s

# target to generate assembly for a file
src/arp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netGui.dir/build.make CMakeFiles/netGui.dir/src/arp.cpp.s
.PHONY : src/arp.cpp.s

src/ethernet.o: src/ethernet.cpp.o
.PHONY : src/ethernet.o

# target to build an object file
src/ethernet.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netGui.dir/build.make CMakeFiles/netGui.dir/src/ethernet.cpp.o
.PHONY : src/ethernet.cpp.o

src/ethernet.i: src/ethernet.cpp.i
.PHONY : src/ethernet.i

# target to preprocess a source file
src/ethernet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netGui.dir/build.make CMakeFiles/netGui.dir/src/ethernet.cpp.i
.PHONY : src/ethernet.cpp.i

src/ethernet.s: src/ethernet.cpp.s
.PHONY : src/ethernet.s

# target to generate assembly for a file
src/ethernet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netGui.dir/build.make CMakeFiles/netGui.dir/src/ethernet.cpp.s
.PHONY : src/ethernet.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netGui.dir/build.make CMakeFiles/netGui.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netGui.dir/build.make CMakeFiles/netGui.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netGui.dir/build.make CMakeFiles/netGui.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/netgui_actions.o: src/netgui_actions.cpp.o
.PHONY : src/netgui_actions.o

# target to build an object file
src/netgui_actions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netGui.dir/build.make CMakeFiles/netGui.dir/src/netgui_actions.cpp.o
.PHONY : src/netgui_actions.cpp.o

src/netgui_actions.i: src/netgui_actions.cpp.i
.PHONY : src/netgui_actions.i

# target to preprocess a source file
src/netgui_actions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netGui.dir/build.make CMakeFiles/netGui.dir/src/netgui_actions.cpp.i
.PHONY : src/netgui_actions.cpp.i

src/netgui_actions.s: src/netgui_actions.cpp.s
.PHONY : src/netgui_actions.s

# target to generate assembly for a file
src/netgui_actions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netGui.dir/build.make CMakeFiles/netGui.dir/src/netgui_actions.cpp.s
.PHONY : src/netgui_actions.cpp.s

src/tap.o: src/tap.cpp.o
.PHONY : src/tap.o

# target to build an object file
src/tap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netGui.dir/build.make CMakeFiles/netGui.dir/src/tap.cpp.o
.PHONY : src/tap.cpp.o

src/tap.i: src/tap.cpp.i
.PHONY : src/tap.i

# target to preprocess a source file
src/tap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netGui.dir/build.make CMakeFiles/netGui.dir/src/tap.cpp.i
.PHONY : src/tap.cpp.i

src/tap.s: src/tap.cpp.s
.PHONY : src/tap.s

# target to generate assembly for a file
src/tap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netGui.dir/build.make CMakeFiles/netGui.dir/src/tap.cpp.s
.PHONY : src/tap.cpp.s

src/tui_app.o: src/tui_app.cpp.o
.PHONY : src/tui_app.o

# target to build an object file
src/tui_app.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netGui.dir/build.make CMakeFiles/netGui.dir/src/tui_app.cpp.o
.PHONY : src/tui_app.cpp.o

src/tui_app.i: src/tui_app.cpp.i
.PHONY : src/tui_app.i

# target to preprocess a source file
src/tui_app.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netGui.dir/build.make CMakeFiles/netGui.dir/src/tui_app.cpp.i
.PHONY : src/tui_app.cpp.i

src/tui_app.s: src/tui_app.cpp.s
.PHONY : src/tui_app.s

# target to generate assembly for a file
src/tui_app.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netGui.dir/build.make CMakeFiles/netGui.dir/src/tui_app.cpp.s
.PHONY : src/tui_app.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... netGui"
	@echo "... src/arp.o"
	@echo "... src/arp.i"
	@echo "... src/arp.s"
	@echo "... src/ethernet.o"
	@echo "... src/ethernet.i"
	@echo "... src/ethernet.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/netgui_actions.o"
	@echo "... src/netgui_actions.i"
	@echo "... src/netgui_actions.s"
	@echo "... src/tap.o"
	@echo "... src/tap.i"
	@echo "... src/tap.s"
	@echo "... src/tui_app.o"
	@echo "... src/tui_app.i"
	@echo "... src/tui_app.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

